apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-node-app.fullname" . }}
  labels:
    {{- include "sre-node-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "sre-node-app.selectorLabels" . | nindent 4 }}